#!/usr/bin/env bash
#MISE description="Build and deploy to Cloudflare Workers"
#MISE dir="{{config_root}}"

set -euo pipefail

NODE_ENV=production pnpm astro build
NODE_ENV=production pnpm wrangler deploy
